"""Validated, immutable models for the sensorsearch TOML configuration."""

from rdmo_sensorsearch.config_models.contracts import (
    BOOLEAN_SETTINGS,
    CATALOG_SCOPE_KEYS,
    COMMON_HANDLER_SETTINGS,
    COMMON_PROVIDER_SETTINGS,
    CONFIGURATION_MEMBERSHIP_SETTINGS,
    CONFIGURATION_PROVIDER_NAMES,
    DEVICE_DETAIL_SETTINGS,
    DEVICE_PROVIDER_NAMES,
    HANDLER_DEFAULT_ID_PREFIXES,
    HANDLER_SETTINGS,
    POSITIVE_INTEGER_SETTINGS,
    PROVIDER_DEFAULT_ID_PREFIXES,
    PROVIDER_HANDLER_NAMES,
    PROVIDER_SETTINGS,
    STRING_SEQUENCE_SETTINGS,
    TOP_LEVEL_SECTIONS,
)
from rdmo_sensorsearch.config_models.models import (
    CatalogScopeConfig,
    DataCollectionSyncCatalogConfig,
    DataCollectionVariableSyncConfig,
    HandlerCatalogConfig,
    HandlerConfig,
    MetadataRefreshActionConfig,
    MetadataRefreshConfig,
    PluginConfig,
    ProjectOptionsCatalogConfig,
    ProjectOptionsProviderConfig,
    ProviderInstanceConfig,
    SearchProviderConfig,
)
from rdmo_sensorsearch.config_models.parsing import parse_plugin_config
from rdmo_sensorsearch.config_models.validation import ConfigValidationError

__all__ = (
    "BOOLEAN_SETTINGS",
    "CATALOG_SCOPE_KEYS",
    "COMMON_HANDLER_SETTINGS",
    "COMMON_PROVIDER_SETTINGS",
    "CONFIGURATION_MEMBERSHIP_SETTINGS",
    "CONFIGURATION_PROVIDER_NAMES",
    "DEVICE_DETAIL_SETTINGS",
    "DEVICE_PROVIDER_NAMES",
    "HANDLER_DEFAULT_ID_PREFIXES",
    "HANDLER_SETTINGS",
    "POSITIVE_INTEGER_SETTINGS",
    "PROVIDER_DEFAULT_ID_PREFIXES",
    "PROVIDER_HANDLER_NAMES",
    "PROVIDER_SETTINGS",
    "STRING_SEQUENCE_SETTINGS",
    "TOP_LEVEL_SECTIONS",
    "CatalogScopeConfig",
    "ConfigValidationError",
    "DataCollectionSyncCatalogConfig",
    "DataCollectionVariableSyncConfig",
    "HandlerCatalogConfig",
    "HandlerConfig",
    "MetadataRefreshActionConfig",
    "MetadataRefreshConfig",
    "PluginConfig",
    "ProjectOptionsCatalogConfig",
    "ProjectOptionsProviderConfig",
    "ProviderInstanceConfig",
    "SearchProviderConfig",
    "parse_plugin_config",
)
