#!/usr/bin/env python3
"""Generate the independent plugin-development catalog and TOML fixture.

The source catalog remains authoritative.  The test-only TOML fixture is a
fully isolated profile so production ``sensorsearch.toml`` never needs example
catalog mappings.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from xml.etree import ElementTree

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from testing.paths import CATALOGS_ROOT, FIXTURES_ROOT, PRODUCTION_CONFIG_PATH, REPOSITORY_ROOT

ROOT = REPOSITORY_ROOT
SOURCE_CATALOG = CATALOGS_ROOT / "earth-sensor+original.xml"
TARGET_CATALOG = CATALOGS_ROOT / "example_catalog_sensorsearch.xml"
SOURCE_CONFIG = PRODUCTION_CONFIG_PATH
TARGET_CONFIG = FIXTURES_ROOT / "sensorsearch-plugin-dev.toml"
DC_URI = "{http://purl.org/dc/elements/1.1/}uri"
SOURCE_CATALOG_URI = "https://rdmo.nfdi4earth.de/terms/questions/earth-sensor"
TARGET_CATALOG_URI = "https://example.com/terms/questions/plugin-dev/sensorsearch"
PLUGIN_DEV_ATTRIBUTE_URI = "https://example.com/terms/domain/plugin-dev"
NORMAL_URI = re.compile(r"^https?://[^/]+/terms/(questions|domain|options|conditions)/(.*)$")
LEGACY_URI = re.compile(r"^https?://[^/]+/(domain|options)/(.*)$")


def mirror_uri(uri: str) -> str:
    """Return the independent plugin-development URI for a source URI."""

    if uri == SOURCE_CATALOG_URI:
        return TARGET_CATALOG_URI
    if match := NORMAL_URI.match(uri):
        return f"https://example.com/terms/{match.group(1)}/plugin-dev/{match.group(2)}"
    if match := LEGACY_URI.match(uri):
        return f"https://example.com/terms/{match.group(1)}/plugin-dev/{match.group(2)}"
    return uri


def _plugin_path(path: str | None, *, catalog: bool = False) -> str | None:
    if path is None:
        return None
    stripped = path.strip().strip("/")
    if catalog:
        return "plugin-dev/sensorsearch"
    return f"plugin-dev/{stripped}" if stripped else "plugin-dev"


def generate_catalog() -> bytes:
    parser = ElementTree.XMLParser(target=ElementTree.TreeBuilder(insert_comments=True))
    root = ElementTree.parse(SOURCE_CATALOG, parser=parser).getroot()
    ElementTree.register_namespace("dc", "http://purl.org/dc/elements/1.1/")

    for element in root.iter():
        uri = element.attrib.get(DC_URI)
        if uri:
            element.attrib[DC_URI] = mirror_uri(uri)

    for element in root:
        original_uri = element.attrib.get(DC_URI, "")
        if not original_uri.startswith("https://example.com/"):
            continue
        prefix = element.find("uri_prefix")
        if prefix is not None:
            prefix.text = "https://example.com/terms"
        for child_name in ("uri_path", "path"):
            child = element.find(child_name)
            if child is not None:
                child.text = _plugin_path(child.text, catalog=original_uri == TARGET_CATALOG_URI)

    source_root_attributes = [
        element
        for element in root
        if element.tag == "attribute" and (parent := element.find("parent")) is not None and DC_URI not in parent.attrib
    ]
    for attribute in source_root_attributes:
        attribute.find("parent").attrib[DC_URI] = PLUGIN_DEV_ATTRIBUTE_URI

    plugin_dev_root = ElementTree.Element("attribute", {DC_URI: PLUGIN_DEV_ATTRIBUTE_URI})
    ElementTree.SubElement(plugin_dev_root, "uri_prefix").text = "https://example.com/terms"
    ElementTree.SubElement(plugin_dev_root, "key").text = "plugin-dev"
    ElementTree.SubElement(plugin_dev_root, "path").text = "plugin-dev"
    ElementTree.SubElement(plugin_dev_root, "{http://purl.org/dc/elements/1.1/}comment")
    ElementTree.SubElement(plugin_dev_root, "parent")
    root.insert(1, plugin_dev_root)

    ElementTree.indent(root, space="  ")
    return b'<?xml version="1.0" encoding="utf-8"?>\n' + ElementTree.tostring(root, encoding="utf-8") + b"\n"


def generate_config() -> bytes:
    source = SOURCE_CONFIG.read_text(encoding="utf-8")
    transformed = re.sub(r"https?://[^\"'\s]+", lambda match: mirror_uri(match.group(0)), source)
    transformed = transformed.replace(
        "[[DeviceDetailSync.catalogs]]\n",
        f'[[DeviceDetailSync.catalogs]]\ncatalog_uri = "{TARGET_CATALOG_URI}"\n',
        1,
    )
    header = (
        "# This file is generated by testing/tools/generate_plugin_dev_assets.py.\n"
        "# It is a test/example-only complete profile for testing/catalogs/example_catalog_sensorsearch.xml.\n"
        "# Do not copy its example.com bindings into the production sensorsearch.toml.\n\n"
    )
    return (header + transformed).encode("utf-8")


def _write_or_check(path: Path, content: bytes, check: bool) -> bool:
    if path.exists() and path.read_bytes() == content:
        return True
    if check:
        print(f"outdated generated asset: {path.relative_to(ROOT)}")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated assets are not current")
    args = parser.parse_args()
    catalog_ok = _write_or_check(TARGET_CATALOG, generate_catalog(), args.check)
    config_ok = _write_or_check(TARGET_CONFIG, generate_config(), args.check)
    return 0 if catalog_ok and config_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
